name: hello
on: workflow_dispatch
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: salahuddin
       run:  echo "git hub actions"
         
  test:
   runs-on: ubuntu-latest
   steps:
     - name: salahuddin
       run:  echo "test"
   deploy:
    runs-on: ubuntu-latest
   steps:
     - name: salahuddin
       run:  echo "deploy"
  
              
              
                 
